# Generated by Django 3.2.5 on 2023-03-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveThruOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('order_time', models.IntegerField()),
                ('pickup_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
            ],
        ),
    ]
